#[derive(Clone, Debug)]
pub struct PendingLastKill {
    pub confirmation_frames_remaining: u8,
    pub kill_count: u16,
    pub is_headshot: bool,
    pub is_knife_kill: bool,
    pub is_grenade_kill: bool,
    pub weapon_badge_key: Option<String>,
    pub weapon_name: Option<String>,
    pub money_reward: u16,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct WeaponKillContext {
    pub inventory_key: String,
    pub is_knife: bool,
    pub badge_key: Option<String>,
    pub name: String,
    pub money_reward: u16,
}

/// Custom bomb audio file paths. Empty strings mean "use the built-in sound".
#[derive(Clone, Default)]
pub struct BombAudioPaths {
    pub timer: String,
    pub exploded: String,
    pub defused: String,
}

pub struct AppState {
    pub mutable: RwLock<Mutable>,
    pub control_token: String,
    pub stream_handle: RwLock<OutputStream>,
    pub current_output_device_name: RwLock<String>,
    pub selected_output_device_name: RwLock<String>,
    pub args: Args,
    pub preset: RwLock<Preset>,
    pub volume_percent: AtomicU32,
    pub streak_gain_enabled: AtomicBool,
    pub streak_gain_step_percent: AtomicU32,
    pub streak_gain_maximum_percent: AtomicU32,
    pub money_reward_mode: AtomicU8,
    pub crossfire_streak_mode: AtomicU8,
    pub crossfire_streak_window_ms: AtomicU64,
    pub crossfire_mode_active: AtomicBool,
    pub shared_streak_mode: AtomicU8,
    pub shared_streak_window_ms: AtomicU64,
    pub shared_streak_mode_active: AtomicBool,
    pub crossfire_first_kill_special_audio: AtomicBool,
    pub crossfire_last_kill_special_audio: AtomicBool,
    pub crossfire_headshot_special_audio_priority: AtomicBool,
    pub crossfire_knife_special_audio_priority: AtomicBool,
    pub assist_audio_enabled: AtomicBool,
    pub assist_audio_setting_active: AtomicBool,
    pub event_sound_settings: RwLock<EventSoundSettings>,
    pub csol_voice_picks: RwLock<HashMap<String, String>>,
    pub csol_special_voice_priority: AtomicBool,
    pub csol_last_kill_special_audio: AtomicBool,
    pub dagoujiao_epic_kill_count: AtomicU32,
    pub dagoujiao_headshot_priority: AtomicBool,
    pub dagoujiao_initial_playback_speed_percent: AtomicU32,
    pub dagoujiao_maximum_playback_speed_percent: AtomicU32,
    pub dagoujiao_epic_playback_speed_percent: AtomicU32,
    pub dagoujiao_audio_paths: RwLock<HashMap<String, String>>,
    pub doubao_audio_paths: RwLock<HashMap<String, String>>,
    pub bomb_audio_enabled: AtomicBool,
    pub bomb_audio_volume_percent: AtomicU32,
    pub bomb_audio_initial_speed_percent: AtomicU32,
    pub bomb_audio_final_speed_percent: AtomicU32,
    pub bomb_audio_generation: AtomicU64,
    pub bomb_audio_sink: std::sync::Mutex<Option<Arc<rodio::Sink>>>,
    pub stop_previous_kill_audio: AtomicBool,
    pub kill_audio_sinks: std::sync::Mutex<Vec<Arc<Sink>>>,
    pub spectated_kill_effects_enabled: AtomicBool,
    pub bomb_audio_paths: std::sync::Mutex<BombAudioPaths>,
    pub gsi_game_version: AtomicU8,
    pub events: EventJournal,
    pub ui_process_ids: RwLock<HashSet<u32>>,
    pub shutdown_tx: broadcast::Sender<()>,
    pub gsi_posts: AtomicU64,
    pub gsi_parse_errors: AtomicU64,
    pub last_gsi_post_unix_ms: AtomicU64,
    pub last_gsi_parse_error_unix_ms: AtomicU64,
}
